### ISSUE TITLE
some time my code not updated properly.

### ISSUE THREAD

**Issue by Sooraj-s-98** [codedamn/codedamn-hacktoberfest-projects#258]
i faced this issue many  times. i checked API response. when i click on UPDATE PROJECT button. API called but after some time API failed. yesterday morning i updated my code. when i open some code in night . my morning change is missing. Same issue faced many times. some time image Drag upload not working. I dont know . what is the problem.

**Comment by vinayvikram** [comment]
I also faced the same problem..
It seems that update project is not working welll.
But the code had been saved automatically in the IDE in my case.
I don't think you need to update the project.. simply code in the IDE and it will be saved.
Sometimes you will get notification that the connection has been lost, then simply re-connect.

**Comment by Sooraj-s-98** [comment]
> I also faced the same problem.. It seems that update project is not working welll. But the code had been saved automatically in the IDE in my case. I don't think you need to update the project.. simply code in the IDE and it will be saved. Sometimes you will get notification that the connection has been lost, then simply re-connect.

But updated code missing

**Comment by vinayvikram** [comment]
Hope someone from codedamn team will fix issue..

Meanwhile, you can code in other IDE and simply paste in the codedamn IDE..

**Comment by Sooraj-s-98** [comment]
> Hope someone from codedamn team will fix issue..
> 
> Meanwhile, you can code in other IDE and simply paste in the codedamn IDE..

currently save code in local . Then only submit.

**Comment by mehulmpt** [comment]
Thank you for reporting this. An update from the team is that we're working towards shipping an update that should fix problems with file saving and code changes by tonight.
