### ISSUE TITLE
Small doubt 

### ISSUE THREAD

**Issue by DarshGupta1910** [codedamn/codedamn-hacktoberfest-projects#26]
this is really a great initiative from @mehulmpt. I just had a small doubt if my PR gets merged will that also be counted for Hactoberfest?

Thank you.

**Comment by SanthoshS20** [comment]
I don't think so. Please check this link https://hacktoberfest.digitalocean.com/profile

If this is showing project not participating - Then it will not be counted

**Comment by DarshGupta1910** [comment]
ok thanks @SanthoshS20

**Comment by ishikkkkaaaa** [comment]
@DarshGupta1910 Yes, the PR merged will be counted under Hacktober fest.

**Comment by DarshGupta1910** [comment]
ok cool. thanks @ishikkkkaaaa
