### ISSUE TITLE
Negative like count. Please add some conditions

### ISSUE THREAD

**Issue by Sooraj-s-98** [codedamn/codedamn-hacktoberfest-projects#302]
![Screenshot_2021-10-07-06-16-47-76_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/52352285/136303302-133c43fe-cbf8-4bd3-85d9-f58907e86f32.jpg)

**Comment by Sooraj-s-98** [comment]
It is only ui issue. You can like another person post unlimeted times. And you can like you submission negatively

**Comment by Code-Aditya-14** [comment]
Hello,
Can I work on this issue @Sooraj-s-98 .

**Comment by mehulmpt** [comment]
Hello @Sooraj-s-98 
Thank you for pointing this out.
We checked our implementation and we do not store the "likes" counter. It is computed on the basis of the length of array of users who liked it. What you're seeing is a caching issue. This should be fixed now and should not show wrong values for any page.
