### ISSUE TITLE
This repository is showing excluded in Hacktoberfest

### ISSUE THREAD

**Issue by idivyanshbansal** [codedamn/codedamn-hacktoberfest-projects#380]
![Screenshot 2021-10-09 195114](https://user-images.githubusercontent.com/86911142/136661890-df7f437b-8e58-40f0-a7ba-8d6ecf973109.png)

**Comment by mehulmpt** [comment]
Please read the FAQ section on README.md

**Comment by mehulmpt** [comment]
I'm sorry I couldn't understand what you mean. DigitalOcean rules do not apply to this competition organized by codedamn if they have excluded the repo, right? There's no 14-day mature-period here

**Comment by idivyanshbansal** [comment]
> I'm sorry I couldn't understand what you mean. DigitalOcean rules do not apply to this competition organized by codedamn if they have excluded the repo, right? There's no 14-day mature-period here

Okay @mehulmpt
