### ISSUE TITLE
Just a not so Important Question related to the Contest 

### ISSUE THREAD

**Issue by justaman045** [codedamn/codedamn-hacktoberfest-projects#577]
As One of my PR got Merged 😁 then I got a comment on that PR by one of the person from the CODEDAMN team that My PR has been Merged and the team will contact me after the contest 😍

So I was just having an eye on the other devs projects which have been merged 

So on some of them it was written like the team will contact them after the contest gets over and also after checking their code

But that ( *after checking your Code* ) wasn't written on mine PR response

So is it like the Code check has to be done after the contest or the Code check was to be done before the PR was to be merged??

Just feeling nervous after seeing this as the Hacktoberfest just excluded my many of the repo ( on which I had contributed ) and now I think that I won't be able to get this years SWAG from the Hacktoberfest and I was assuming the SWAG from the CODEDAMN team will be my assured SWAG ( as @mehulmpt  said ) [here](https://github.com/codedamn/codedamn-hacktoberfest-projects#the-repository-is-not-included-in-digitalocean-hacktoberfest) If I got the meaning right

**Comment by gaurav26-coder** [comment]
Hi I and many others have submitted pull request for long time but no one accepting for merge, can you help us.

**Comment by mehulmpt** [comment]
@gaurav26-coder @coderaman07 Please there's no benefit of pinging/creating a new issue only for merge requests. We can see the number of pending PRs and we intend to merge or close all PRs submitted before October ends.

**Comment by mehulmpt** [comment]
@coderaman07 If your PR is merged, it does not matter if anyone commented on it or not
