### ISSUE TITLE
I am unable to clone or pull by adding remote

### ISSUE THREAD

**Issue by sayyamgatagat** [codedamn/codedamn-hacktoberfest-projects#819]
![image](https://user-images.githubusercontent.com/48188738/139540820-7b6e3238-0103-4b16-9403-5df800f664e6.png)
getting this error
What should I do

**Comment by Lakshit-Chiranjiv** [comment]
I am having the same issue. On cloning, I find the repo folder empty with just the .git folder in it.

**Comment by Dev2212** [comment]
just use the GitHub website to add file rather than git then and also fork the repo first.

**Comment by Lakshit-Chiranjiv** [comment]
Its okay....but what is the reason for that issue, why can't we clone it correctly....just curious
